# Deploy VSX Extension
# Based on: https://github.com/HaaLeo/publish-vscode-extension
name: Build and deploy Extension

on:
  # Run when new version ('v*') tag is created
  push:
    tags:
      - "v*"

env:
  NODE_VERSION: '14.x'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      vsixPath: ${{ steps.packageExtension.outputs.vsixPath }}
    steps:
      - uses: actions/checkout@v2.4
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install npm packages
        run: npm ci

      # Check (and update if necessary) package.json version
      - name: Check package version
        uses: technote-space/package-version-check-action@v1.5.2
      
      - name: Package extension .vsix
        id: packageExtension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: stub
          dryRun: true

      - name: Upload extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension-vsix
          path: ${{ steps.packageExtension.outputs.vsixPath }}
      

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      # Pulbish to Open VSX Registry
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ needs.build.outputs.vsixPath }}
          registryUrl: https://open-vsx.org
      
      # Publish to VS Marketplace
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          extensionFile: ${{ steps.build.outputs.vsixPath }}
          registryUrl: https://marketplace.visualstudio.com
