# Deploy VSX Extension
# Based on: https://github.com/HaaLeo/publish-vscode-extension
name: Deploy Extension

# Run when new version ('v*') tag is created 
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci

      # Check (and update if necessary) package.json version
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        
      # Pulbish to Open VSX Registry
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      
      # Publish to VS Marketplace
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          packagePath: ''
