# Deploy VSX Extension
# Based on: https://github.com/HaaLeo/publish-vscode-extension
name: Deploy Extension

# Run when new version ('v*') tag is created 
on:
  push:
    tags:
      - "v*"

env:
  NODE_VERSION: '12.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci

      # Check (and update if necessary) package.json version
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        
      # Pulbish to Open VSX Registry
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      
      # Publish to VS Marketplace
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          packagePath: ''
          
      # Download the built .vsix extension file
      - name: Download .VSIX file
        uses: actions/download-artifact@v2.0.8
        with:
          path: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
